export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_USER = 'GET_USER';
export const GET_USERS = 'GET_USERS';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';