export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_USER = 'GET_USER';
export const GET_USERS = 'GET_USERS';
export const USER_LOADING = 'USER_LOADING';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';

export const GET_ENTERPRISE = 'GET_ENTERPRISE';
export const GET_ENTERPRISES = 'GET_ENTERPRISES';
export const ENTERPRISE_LOADING = 'ENTERPRISE_LOADING';
export const ENTERPRISE_NOT_FOUND = 'ENTERPRISE_NOT_FOUND';

export const GET_FOOD = 'GET_FOOD';
export const GET_FOODS = 'GET_FOODS';
export const FOOD_LOADING = 'FOOD_LOADING';
export const FOOD_NOT_FOUND = 'FOOD_NOT_FOUND';

export const GET_BRANCH = 'GET_BRANCH';
export const GET_BRANCHES = 'GET_BRANCHES';
export const BRANCH_LOADING = 'BRANCH_LOADING';
export const BRANCH_NOT_FOUND = 'BRANCH_NOT_FOUND';

export const GET_ROLE = 'GET_ROLE';
export const GET_ROLES = 'GET_ROLES';
export const ROLE_LOADING = 'ROLE_LOADING';
export const ROLE_NOT_FOUND = 'ROLENOT_FOUND';

export const GET_WALLET = 'GET_WALLET';
export const GET_WALLETS = 'GET_WALLETS';
export const WALLET_LOADING = 'WALLET_LOADING';
export const WALLET_NOT_FOUND = 'WALLET_NOT_FOUND';

export const GET_FOODCATEGORY = 'GET_FOODCATEGORY';
export const GET_FOODCATEGORIES = 'GET_FOODCATEGORIES';
export const FOODCATEGORY_LOADING = 'FOODCATEGORY_LOADING';
export const FOODCATEGORY_NOT_FOUND = 'FOODCATEGORY_NOT_FOUND';

export const GET_MEMBERSHIP = 'GET_MEMBERSHIP';
export const GET_MEMBERSHIPS = 'GET_MEMBERSHIPS';
export const MEMBERSHIP_LOADING = 'MEMBERSHIP_LOADING';
export const MEMBERSHIP_NOT_FOUND = 'MEMBERSHIP_NOT_FOUND';

export const GET_ORDER = 'GET_ORDER';
export const GET_ORDERS = 'GET_ORDERS';
export const ORDER_LOADING = 'ORDER_LOADING';
export const ORDER_NOT_FOUND = 'ORDER_NOT_FOUND';